import React from 'react'
import {Box, VStack, } from '@chakra-ui/react'
import Head from 'next/head'
import NavBar from '../components/NavBar'

type Props = {
    children: React.ReactElement
}

const MainLayout = (props: Props) => {
  return (
    <Box pb={8}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack gap={16}>
        <NavBar />
        {props.children}
      </VStack>
    </Box>
  )
}

export default MainLayout